version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
      # install packages
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install   
      # build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - attach_workspace:
          at: .
      - node/install:
          node-version: '16.13'
      - aws-cli/setup
      - aws-elastic-beanstalk/setup
      - run:
          name: Back-End Deploy
          command: |
            npm run backend:deploy
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy
workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: [main, master]
      - deploy:
          filters:
            branches:
              only: [main, master]
          requires:
            - build
                