version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      # install packages
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install   
      # build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - persist_to_workspace:
          root: ~/udagram
          paths:
            - .
  deploy:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: ~/udagram
      - node/install:
          node-version: '16.13'
      - aws-cli/setup
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build